local Config = {
    BUTTON_WIDTH = 100,
    BUTTON_HEIGHT = 40,
    GRID_SIZE = 30,
    GRID_WIDTH = 10,
    GRID_HEIGHT = 20,
    INITIAL_DROP_TIME = 2.0,
    LEVEL_LINES_REQUIREMENT = 10,
    SPEED_INCREASE_FACTOR = 0.9
}

Config.BUTTON_X = (Config.GRID_WIDTH * Config.GRID_SIZE) + 20
Config.BUTTON_Y = 20

return Config